name: First Workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hi Siva"
      - name: Print GoodBye
        run: echo "bye bue"
        
