name: Second Workflow
on:
    workflow_dispatch:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Ensure lockfile exists
        run: |
          if [ ! -f package-lock.json ]; then
           echo "package-lock.json is missing!"
           exit 1
          fi
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
        
